#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# convert_wcwidth.py — parse include/widechar_width.hpp interval tables and
# emit src-rust/btop-tools/src/wcwidth.rs.
#
# The C++ file is trivially parseable: ten
# `static const struct widechar_range widechar_<name>_table[] = { ... };`
# blocks with `{0xLO, 0xHI}` entries, plus `widechar_wcwidth()` which checks
# the tables in a fixed priority order (see ORDER below) via binary search
# (`widechar_in_table`: lower_bound on hi, then lo <= c). The generated Rust
# mirrors that order exactly, so overlapping entries (e.g. U+4E2D is in both
# `doublewide` and `unassigned`, U+0301 in both `combining` and `ambiguous`)
# resolve identically.
#
# Usage: python3 src-rust/tools/convert_wcwidth.py
# (run from the repo root; paths are relative to it). Stdlib only.
# Then run `cargo fmt` in src-rust/ (rustfmt collapses short tables to one
# line; the committed output is the fmt'd form).
"""Convert widechar_width.hpp interval tables to Rust."""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SRC = ROOT / "include" / "widechar_width.hpp"
DST = ROOT / "src-rust" / "btop-tools" / "src" / "wcwidth.rs"

# (table name, rust const name, width result) in widechar_wcwidth() check order.
ORDER = [
    ("ascii", "ASCII", 1),
    ("private", "PRIVATE", 1),
    ("nonprint", "NONPRINT", 0),
    ("nonchar", "NONCHAR", 0),
    ("combining", "COMBINING", 0),
    ("combiningletters", "COMBINING_LETTERS", 0),
    ("doublewide", "DOUBLEWIDE", 2),
    ("ambiguous", "AMBIGUOUS", 1),
    ("unassigned", "UNASSIGNED", 0),
    ("widened", "WIDENED", 2),
]


def parse_tables(text):
    found = {}
    for m in re.finditer(
        r"widechar_(\w+)_table\[\] = \{(.*?)\};", text, re.S
    ):
        name, body = m.group(1), m.group(2)
        ranges = [
            (int(lo, 16), int(hi, 16))
            for lo, hi in re.findall(
                r"\{0x([0-9A-Fa-f]+),\s*0x([0-9A-Fa-f]+)\}", body
            )
        ]
        if not ranges:
            sys.exit(f"convert_wcwidth: table {name!r} parsed empty — abort")
        found[name] = ranges
    missing = [n for n, _, _ in ORDER if n not in found]
    if missing:
        sys.exit(f"convert_wcwidth: missing tables {missing} — abort")
    return found


def check_sorted(name, ranges):
    for (lo1, hi1), (lo2, hi2) in zip(ranges, ranges[1:]):
        if (lo1, hi1) > (lo2, hi2) or hi1 >= lo2:
            sys.exit(
                f"convert_wcwidth: table {name!r} not sorted/disjoint at "
                f"{lo1:#x}-{hi1:#x} vs {lo2:#x}-{hi2:#x} — abort"
            )


def emit(found):
    lines = []
    lines.append("//! Terminal column widths (Unicode 17.0.0).")
    lines.append("//!")
    lines.append("//! GENERATED by src-rust/tools/convert_wcwidth.py from")
    lines.append("//! include/widechar_width.hpp — do NOT hand-edit.")
    lines.append("//! Lookup order matches C++ `widechar_wcwidth()` exactly:")
    lines.append("//! ascii(1) -> private(1) -> nonprint(0) -> nonchar(0) ->")
    lines.append("//! combining(0) -> combiningletters(0) -> doublewide(2) ->")
    lines.append("//! ambiguous(1) -> unassigned(0) -> widened(2), else 1.")
    lines.append("")
    for name, const, _ in ORDER:
        ranges = found[name]
        check_sorted(name, ranges)
        lines.append(f"const {const}: &[(u32, u32)] = &[")
        for lo, hi in ranges:
            lines.append(f"    (0x{lo:05X}, 0x{hi:05X}),")
        lines.append("];")
        lines.append("")
    lines.append("fn in_table(table: &[(u32, u32)], c: u32) -> bool {")
    lines.append("    // Mirrors widechar_in_table: lower_bound on hi, then lo <= c.")
    lines.append("    let idx = table.partition_point(|&(_, hi)| hi < c);")
    lines.append("    idx < table.len() && table[idx].0 <= c")
    lines.append("}")
    lines.append("")
    lines.append("/// Column width of `ch`: 0 (control/combining), 1, or 2 (CJK/wide).")
    lines.append("/// Mirrors `widechar_wcwidth()` (include/widechar_width.hpp).")
    lines.append("pub fn width(ch: char) -> usize {")
    lines.append("    let c = ch as u32;")
    for name, const, w in ORDER:
        lines.append(f"    if in_table({const}, c) {{")
        lines.append(f"        return {w};")
        lines.append("    }")
    lines.append("    1")
    lines.append("}")
    lines.append("")
    lines.append("#[cfg(test)]")
    lines.append("mod tests {")
    lines.append("    use super::*;")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn ascii_is_single_width() {")
    lines.append('        assert_eq!(width(\'A\'), 1); // ascii table')
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn cjk_is_double_width() {")
    lines.append("        // U+4E2D is in doublewide AND unassigned;")
    lines.append("        // doublewide wins by check order -> 2.")
    lines.append("        assert_eq!(width('\\u{4E2D}'), 2);")
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn combining_is_zero_width() {")
    lines.append("        // U+0301 is in combining AND ambiguous;")
    lines.append("        // combining wins by check order -> 0.")
    lines.append("        assert_eq!(width('\\u{301}'), 0);")
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn emoji_spot_width() {")
    lines.append("        // U+1F600 appears ONLY in the widened table -> 2")
    lines.append("        // (read from the table, not assumed).")
    lines.append("        assert_eq!(width('\\u{1F600}'), 2);")
    lines.append("    }")
    lines.append("")
    lines.append("    #[test]")
    lines.append("    fn controls_are_zero_width() {")
    lines.append("        assert_eq!(width('\\0'), 0); // nonprint table")
    lines.append("        assert_eq!(width('\\u{1B}'), 0); // nonprint table")
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    text = SRC.read_text()
    found = parse_tables(text)
    DST.write_text(emit(found))
    total = sum(len(found[n]) for n, _, _ in ORDER)
    print(f"convert_wcwidth: wrote {DST} ({total} ranges, 10 tables)")


if __name__ == "__main__":
    main()
